dist:
  - trusty
sudo:
  - required
addons:
  apt:
    packages:
      - qt5-default
      - libqt5xmlpatterns5-dev
      - libarchive-dev
      - libsndfile1-dev
      - libasound2-dev
      - libjack-jackd2-dev
      - liblo-dev
      - libpulse-dev
      - libcppunit-dev
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ladspa-sdk -y
language:
  - cpp

script:
  - mkdir build && cd build && cmake .. && make
